# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.10

# Default target executed when no arguments are given to make.
default_target: all

.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:


#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:


# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list


# Suppress display of executed commands.
$(VERBOSE).SILENT:


# A target that is always out of date.
cmake_force:

.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/k/Google Drive/PRIVATE/_VUT/3ZS/ISA/isa2018"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/k/Google Drive/PRIVATE/_VUT/3ZS/ISA/isa2018"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache

.PHONY : rebuild_cache/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache

.PHONY : edit_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/k/Google Drive/PRIVATE/_VUT/3ZS/ISA/isa2018/CMakeFiles" "/mnt/k/Google Drive/PRIVATE/_VUT/3ZS/ISA/isa2018/CMakeFiles/progress.marks"
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/k/Google Drive/PRIVATE/_VUT/3ZS/ISA/isa2018/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean

.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named dns-export

# Build rule for target.
dns-export: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 dns-export
.PHONY : dns-export

# fast build rule for target.
dns-export/fast:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/build
.PHONY : dns-export/fast

src/base64.o: src/base64.c.o

.PHONY : src/base64.o

# target to build an object file
src/base64.c.o:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/base64.c.o
.PHONY : src/base64.c.o

src/base64.i: src/base64.c.i

.PHONY : src/base64.i

# target to preprocess a source file
src/base64.c.i:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/base64.c.i
.PHONY : src/base64.c.i

src/base64.s: src/base64.c.s

.PHONY : src/base64.s

# target to generate assembly for a file
src/base64.c.s:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/base64.c.s
.PHONY : src/base64.c.s

src/dns.o: src/dns.c.o

.PHONY : src/dns.o

# target to build an object file
src/dns.c.o:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/dns.c.o
.PHONY : src/dns.c.o

src/dns.i: src/dns.c.i

.PHONY : src/dns.i

# target to preprocess a source file
src/dns.c.i:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/dns.c.i
.PHONY : src/dns.c.i

src/dns.s: src/dns.c.s

.PHONY : src/dns.s

# target to generate assembly for a file
src/dns.c.s:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/dns.c.s
.PHONY : src/dns.c.s

src/ht.o: src/ht.c.o

.PHONY : src/ht.o

# target to build an object file
src/ht.c.o:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/ht.c.o
.PHONY : src/ht.c.o

src/ht.i: src/ht.c.i

.PHONY : src/ht.i

# target to preprocess a source file
src/ht.c.i:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/ht.c.i
.PHONY : src/ht.c.i

src/ht.s: src/ht.c.s

.PHONY : src/ht.s

# target to generate assembly for a file
src/ht.c.s:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/ht.c.s
.PHONY : src/ht.c.s

src/main.o: src/main.c.o

.PHONY : src/main.o

# target to build an object file
src/main.c.o:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/main.c.o
.PHONY : src/main.c.o

src/main.i: src/main.c.i

.PHONY : src/main.i

# target to preprocess a source file
src/main.c.i:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/main.c.i
.PHONY : src/main.c.i

src/main.s: src/main.c.s

.PHONY : src/main.s

# target to generate assembly for a file
src/main.c.s:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/main.c.s
.PHONY : src/main.c.s

src/network.o: src/network.c.o

.PHONY : src/network.o

# target to build an object file
src/network.c.o:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/network.c.o
.PHONY : src/network.c.o

src/network.i: src/network.c.i

.PHONY : src/network.i

# target to preprocess a source file
src/network.c.i:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/network.c.i
.PHONY : src/network.c.i

src/network.s: src/network.c.s

.PHONY : src/network.s

# target to generate assembly for a file
src/network.c.s:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/network.c.s
.PHONY : src/network.c.s

src/network_utils.o: src/network_utils.c.o

.PHONY : src/network_utils.o

# target to build an object file
src/network_utils.c.o:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/network_utils.c.o
.PHONY : src/network_utils.c.o

src/network_utils.i: src/network_utils.c.i

.PHONY : src/network_utils.i

# target to preprocess a source file
src/network_utils.c.i:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/network_utils.c.i
.PHONY : src/network_utils.c.i

src/network_utils.s: src/network_utils.c.s

.PHONY : src/network_utils.s

# target to generate assembly for a file
src/network_utils.c.s:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/network_utils.c.s
.PHONY : src/network_utils.c.s

src/pcap.o: src/pcap.c.o

.PHONY : src/pcap.o

# target to build an object file
src/pcap.c.o:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/pcap.c.o
.PHONY : src/pcap.c.o

src/pcap.i: src/pcap.c.i

.PHONY : src/pcap.i

# target to preprocess a source file
src/pcap.c.i:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/pcap.c.i
.PHONY : src/pcap.c.i

src/pcap.s: src/pcap.c.s

.PHONY : src/pcap.s

# target to generate assembly for a file
src/pcap.c.s:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/pcap.c.s
.PHONY : src/pcap.c.s

src/process.o: src/process.c.o

.PHONY : src/process.o

# target to build an object file
src/process.c.o:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/process.c.o
.PHONY : src/process.c.o

src/process.i: src/process.c.i

.PHONY : src/process.i

# target to preprocess a source file
src/process.c.i:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/process.c.i
.PHONY : src/process.c.i

src/process.s: src/process.c.s

.PHONY : src/process.s

# target to generate assembly for a file
src/process.c.s:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/process.c.s
.PHONY : src/process.c.s

src/syslog.o: src/syslog.c.o

.PHONY : src/syslog.o

# target to build an object file
src/syslog.c.o:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/syslog.c.o
.PHONY : src/syslog.c.o

src/syslog.i: src/syslog.c.i

.PHONY : src/syslog.i

# target to preprocess a source file
src/syslog.c.i:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/syslog.c.i
.PHONY : src/syslog.c.i

src/syslog.s: src/syslog.c.s

.PHONY : src/syslog.s

# target to generate assembly for a file
src/syslog.c.s:
	$(MAKE) -f CMakeFiles/dns-export.dir/build.make CMakeFiles/dns-export.dir/src/syslog.c.s
.PHONY : src/syslog.c.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... rebuild_cache"
	@echo "... dns-export"
	@echo "... edit_cache"
	@echo "... src/base64.o"
	@echo "... src/base64.i"
	@echo "... src/base64.s"
	@echo "... src/dns.o"
	@echo "... src/dns.i"
	@echo "... src/dns.s"
	@echo "... src/ht.o"
	@echo "... src/ht.i"
	@echo "... src/ht.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/network.o"
	@echo "... src/network.i"
	@echo "... src/network.s"
	@echo "... src/network_utils.o"
	@echo "... src/network_utils.i"
	@echo "... src/network_utils.s"
	@echo "... src/pcap.o"
	@echo "... src/pcap.i"
	@echo "... src/pcap.s"
	@echo "... src/process.o"
	@echo "... src/process.i"
	@echo "... src/process.s"
	@echo "... src/syslog.o"
	@echo "... src/syslog.i"
	@echo "... src/syslog.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

